from .common import NODE_CLASS_MAPPINGS as COMMON_NODE_CLASS_MAPPINGS
from .lora import NODE_CLASS_MAPPINGS as LORA_NODE_CLASS_MAPPINGS
from .dreambooth import NODE_CLASS_MAPPINGS as DREAMBOOTH_NODE_CLASS_MAPPINGS

NODE_CLASS_MAPPINGS = {**COMMON_NODE_CLASS_MAPPINGS, **LORA_NODE_CLASS_MAPPINGS, **DREAMBOOTH_NODE_CLASS_MAPPINGS}

__all__ = ["NODE_CLASS_MAPPINGS"]
